{{- if and .Values.workerMedia.enabled .Values.workerMedia.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ff-indexer.fullname" . }}-worker-media
  labels:
    {{- include "ff-indexer.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker-media
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ff-indexer.fullname" . }}-worker-media
  minReplicas: {{ .Values.workerMedia.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.workerMedia.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.workerMedia.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.workerMedia.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.workerMedia.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.workerMedia.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}

